#define VERSION ARGS.VERSION
#define REVISION ARGS.REVISION
#define VERSIONREVISION "ARGS.VERSION.ARGS.REVISION"
#define DATE 10.11.95
#define VERS "Object ARGS.VERSION.ARGS.REVISION"
#define VSTRING "Object ARGS.VERSION.ARGS.REVISION (10.11.95)\r\n"
#define VERSTAG "$VER:Object ARGS.VERSION.ARGS.REVISION (10.11.95)"
