/* Main-Header File inserted by GenCodeC */
/* Libraries */
#include <libraries/mui.h>

/* Prototypes */
/*
#include <clib/muimaster_protos.h>
#include <clib/alib_protos.h>
#include <clib/dos_protos.h>
#include <clib/exec_protos.h>
#include <clib/gadtools_protos.h> /* for BARLABEL in MenuItem */
*/

/*  Pragmas  */
#ifdef AZTEC_C
#include <pragmas/muimaster_lib.h>
#include <pragmas/exec_lib.h>
#endif /*AZTEC_C*/

#if defined(__SASC)  ||  defined(_DCC)  ||  defined(__MAXON__)
#include <pragmas/muimaster_pragmas.h>
#include <pragmas/exec_pragmas.h>
#endif    /*__SASC||_DCC||__MAXON__*/

#ifdef __GNUC__
#include <proto/exec/h>
#include <proto/alib.h>
#include <proto/muimaster.h>
#include <proto/dos.h>
#include <proto/gadtools.h>
//#include <inline/muimaster.h>
//#include <inline/exec.h>
#endif    /*__GNUC__*/

/*  Ansi  */
#include <stdlib.h>
#include <stdio.h>
/* GenCodeC header end */

/* Include generated by GenCodeC */
#include ",_POLßLNup"

/* Init Function inserted by GenCodeC */
struct Library * MUIMasterBase;

/* Init function */
static void init( void )
{
    if (!(MUIMasterBase = OpenLibrary(MUIMASTER_NAME,MUIMASTER_VMIN)))
    {
        printf("Can't Open MUIMaster Library\n");
        exit(20);
    }
}
/* GenCodeC init end */

/* Main Function inserted by GenCodeC */
int main(int argc,char **argv)
{
    struct ObjApp * App = NULL;    /* Object */
    BOOL    running = TRUE;
    ULONG    signal;

    /* Program initialisation : generated by GenCodeC */
    init();

    /* Create Object : generated by GenCodeC */
    App = CreateApp();
    while (running)
    {
        switch (DoMethod(App->App,MUIM_Application_Input,&signal))
        {
            case MUIV_Application_ReturnID_Quit:
                running = FALSE;
                break;

            /* Insert your code between the "case" statement and the "break" statement */
            /* End computing of IDCMP */
