/***************************************************************************

  MUIBuilder - MUI interface builder
  Copyright (C) 1990-2009 by Eric Totel
  Copyright (C) 2010-2011 by MUIBuilder Open Source Team

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.

  MUIBuilder Support Site: http://sourceforge.net/projects/muibuilder/

  $Id$$

***************************************************************************/

/* Main-Header File inserted by GenCodeC */
/* Libraries */
#include <libraries/mui.h>

/* Prototypes */
#include <proto/exec/h>
#include <proto/alib.h>
#include <proto/muimaster.h>
#include <proto/dos.h>
#include <proto/gadtools.h>

/*  Ansi  */
#include <stdlib.h>
#include <stdio.h>
/* GenCodeC header end */

/* Include generated by GenCodeC */
#include ",_POLßLNup"

/* Init Function inserted by GenCodeC */
struct Library * MUIMasterBase;

/* Init function */
static void init( void )
{
    if (!(MUIMasterBase = OpenLibrary(MUIMASTER_NAME,MUIMASTER_VMIN)))
    {
        printf("Can't Open MUIMaster Library\n");
        exit(20);
    }
}
/* GenCodeC init end */

/* Main Function inserted by GenCodeC */
int main(int argc,char **argv)
{
    struct ObjApp * App = NULL;    /* Object */
    BOOL    running = TRUE;
    ULONG    signal;

    /* Program initialisation : generated by GenCodeC */
    init();

    /* Create Object : generated by GenCodeC */
    App = CreateApp();
    while (running)
    {
        switch (DoMethod(App->App,MUIM_Application_Input,&signal))
        {
            case MUIV_Application_ReturnID_Quit:
                running = FALSE;
                break;

            /* Insert your code between the "case" statement and the "break" statement */
            /* End computing of IDCMP */
