/****************************************************************
   This file was created automatically by `FlexCat V1.0'
   Do NOT edit by hand!
****************************************************************/

#ifndef MUIBuilder_CAT_H
#define MUIBuilder_CAT_H


#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif	/*  !EXEC_TYPES_H	    */
#ifndef LIBRARIES_LOCALE_H
#include <libraries/locale.h>
#endif	/*  !LIBRARIES_LOCALE_H     */


/*  Prototypes	*/
extern void OpenMUIBuilderCatalog(struct Locale *, STRPTR);
extern void CloseMUIBuilderCatalog(void);
extern STRPTR GetMUIBuilderString(LONG);

/*  Definitions */
#define MSG_Application 0
#define MSG_Base 1
#define MSG_Author 2
#define MSG_Title 3
#define MSG_Version 4
#define MSG_Copyright 5
#define MSG_Description 6
#define MSG_Cancel 7
#define MSG_Ok 8
#define MSG_ChoseFunction 9
#define MSG_MergeFile 10
#define MSG_ComeBack 11
#define MSG_ApplicationLost 12
#define MSG_AboutText 13
#define MSG_Failed 14
#define MSG_Arguments 15
#define MSG_NeedWindows 16
#define MSG_NotEnoughMemory 17
#define MSG_SelectWindow 18
#define MSG_Confirm 19
#define MSG_ConfirmExit 20
#define MSG_SelectObject 21
#define MSG_SelectTmpObject 22
#define MSG_RemoveRootGroup 23
#define MSG_QuitWindowAttributes 24
#define MSG_NoChild 25
#define MSG_NothingToUndelete 26
#define MSG_CantMoveRoot 27
#define MSG_NeedLabel 28
#define MSG_NeedLabelTitle 29
#define MSG_NeedImageLabel 30
#define MSG_NeedBase 31
#define MSG_NotBuilderSaveFile 32
#define MSG_WrongVersion 33
#define MSG_SelectEntry 34
#define MSG_NeedLabelEntries 35
#define MSG_SeletNotifyLink 36
#define MSG_NotifyExists 37
#define MSG_SelectAction 38
#define MSG_SelectEvent 39
#define MSG_SelectNotifyLink 40
#define MSG_CantMovePopObjectChild 41
#define MSG_CantDeletePopObjectChild 42
#define MSG_CopyNotImplemented 43
#define MSG_ErrorReading 44
#define MSG_GroupError 45
#define MSG_SelectMenuTitle 46
#define MSG_SelectSubMenu 47
#define MSG_GiveObjectAndLabel 48
#define MSG_AlreadyGenerated 49
#define MSG_SelectLabel 50
#define MSG_RectangleChoices 51
#define MSG_Rectangle 52
#define MSG_HorizontalBar 53
#define MSG_VerticalBar 54
#define MSG_Configuration 55
#define MSG_ConfigChoices 56
#define MSG_GhostWindows 57
#define MSG_Icons 58
#define MSG_Requests 59
#define MSG_Editor 60
#define MSG_Save 61
#define MSG_EditorChoice 62
#define MSG_TestLabel 63
#define MSG_Depth 64
#define MSG_TreeChar 65
#define MSG_WrittenBy 66
#define MSG_Windows 67
#define MSG_Creation 68
#define MSG_Appli 69
#define MSG_NewWindow 70
#define MSG_EditWindow 71
#define MSG_Delete 72
#define MSG_View 73
#define MSG_Code 74
#define MSG_Guide 75
#define MSG_Quit 76
#define MSG_WindowAttributes 77
#define MSG_WindowIdentification 78
#define MSG_Label 79
#define MSG_AddChild 80
#define MSG_RemoveChild 81
#define MSG_Up 82
#define MSG_Down 83
#define MSG_Tmp 84
#define MSG_ToTmp 85
#define MSG_ToChild 86
#define MSG_RemoveTmp 87
#define MSG_Test 88
#define MSG_EditObject 89
#define MSG_Notify 90
#define MSG_Menu 91
#define MSG_Copy 92
#define MSG_CopyTmp 93
#define MSG_OpenAtInit 94
#define MSG_AppWindow 95
#define MSG_Backdrop 96
#define MSG_Borderless 97
#define MSG_CloseGadget 98
#define MSG_DepthGadget 99
#define MSG_DragBar 100
#define MSG_SizeGadget 101
#define MSG_GroupWindow 102
#define MSG_GroupAttributes 103
#define MSG_HorizGroup 104
#define MSG_PageMode 105
#define MSG_SameHeight 106
#define MSG_SameWidth 107
#define MSG_SameSize 108
#define MSG_VirtualGroup 109
#define MSG_Columns 110
#define MSG_Rows 111
#define MSG_HorizSpacing 112
#define MSG_VertSpacing 113
#define MSG_Register 114
#define MSG_RegisterEntries 115
#define MSG_RowsColumns 116
#define MSG_Number 117
#define MSG_Spacing 118
#define MSG_Horizontal 119
#define MSG_Vertical 120
#define MSG_GroupIdent 121
#define MSG_ObjectChoice 122
#define MSG_Group 123
#define MSG_KeyButton 124
#define MSG_ListView 125
#define MSG_DirList 126
#define MSG_String 127
#define MSG_LabelObj 128
#define MSG_Cycle 129
#define MSG_Radio 130
#define MSG_Image 131
#define MSG_Space 132
#define MSG_CheckMark 133
#define MSG_Slider 134
#define MSG_Gauge 135
#define MSG_Scale 136
#define MSG_Text 137
#define MSG_Prop 138
#define MSG_Bar 139
#define MSG_Colorfield 140
#define MSG_PopAsl 141
#define MSG_PopObject 142
#define MSG_LabelIdent 143
#define MSG_LabelChoice 144
#define MSG_Left 145
#define MSG_Right 146
#define MSG_Center 147
#define MSG_StringChoice 148
#define MSG_UseTitle 149
#define MSG_SecretString 150
#define MSG_IntegerString 151
#define MSG_StringIdent 152
#define MSG_Content 153
#define MSG_Accept 154
#define MSG_Reject 155
#define MSG_MaxLen 156
#define MSG_ButtonChoices 157
#define MSG_ButtonIdent 158
#define MSG_ShortKey 159
#define MSG_CheckMarkChoice 160
#define MSG_CheckMarkIdent 161
#define MSG_InitialState 162
#define MSG_CycleChoice 163
#define MSG_CycleEntries 164
#define MSG_New 165
#define MSG_Remove 166
#define MSG_Entry 167
#define MSG_RadioChoices 168
#define MSG_RadioEntries 169
#define MSG_SortbyName 170
#define MSG_SortbyDate 171
#define MSG_SortbySize 172
#define MSG_ListDirChoices 173
#define MSG_Attributes 174
#define MSG_DrawersOnly 175
#define MSG_FilesOnly 176
#define MSG_FilterDrawers 177
#define MSG_MultiSelection 178
#define MSG_RejectIcons 179
#define MSG_SortHighLow 180
#define MSG_SortType 181
#define MSG_Dir 182
#define MSG_SortDirs 183
#define MSG_DirsFirst 184
#define MSG_DirsLast 185
#define MSG_DirsMixed 186
#define MSG_GaugeChoices 187
#define MSG_Choices 188
#define MSG_HorizGauge 189
#define MSG_FixHeight 190
#define MSG_FixWidth 191
#define MSG_Divide 192
#define MSG_Maximum 193
#define MSG_Height 194
#define MSG_Width 195
#define MSG_Infotext 196
#define MSG_MultiplyDefinedLabel 197
#define MSG_MultiDefinitions 198
#define MSG_CodeFileName 199
#define MSG_ObjectsLabels 200
#define MSG_GeneratedLabels 201
#define MSG_AppCode 202
#define MSG_ObjectCode 203
#define MSG_RemoveLabel 204
#define MSG_AddLabel 205
#define MSG_Options 206
#define MSG_Declarations 207
#define MSG_Environment 208
#define MSG_CodeOption 209
#define MSG_NotificationsOption 210
#define MSG_CatalogButton 211
#define MSG_Catalog 212
#define MSG_Locale 213
#define MSG_GetString 214
#define MSG_TextLength 215
#define MSG_NodeTitle 216
#define MSG_EditNodeText 217
#define MSG_CantOpen 218
#define MSG_AmigaGuide 219
#define MSG_Objects 220
#define MSG_Edit 221
#define MSG_Edit2 222
#define MSG_Operations 223
#define MSG_AppNode 224
#define MSG_WindowNode 225
#define MSG_ObjectNode 226
#define MSG_GenerateWholeDoc 227
#define MSG_GenerateWinDoc 228
#define MSG_GenerateObjDoc 229
#define MSG_ViewDoc 230
#define MSG_AmigaguideDocName 231
#define MSG_CantOpenAmigaGuide 232
#define MSG_ImageChoice 233
#define MSG_FreeVertical 234
#define MSG_FreeHorizontal 235
#define MSG_InputMode 236
#define MSG_Frame 237
#define MSG_Size 238
#define MSG_ImageIdent 239
#define MSG_Images 240
#define MSG_ListChoice 241
#define MSG_ListType 242
#define MSG_ListIdent 243
#define MSG_StandardList 244
#define MSG_FloattextList 245
#define MSG_VolumeList 246
#define MSG_NoEntry 247
#define MSG_FirstEntry 248
#define MSG_LastEntry 249
#define MSG_Strings 250
#define MSG_AdjustHeight 251
#define MSG_AdjustWidth 252
#define MSG_Activate 253
#define MSG_DisplayHook 254
#define MSG_ConstructHook 255
#define MSG_DestructHook 256
#define MSG_CompareHook 257
#define MSG_MultiTestHook 258
#define MSG_Format 259
#define MSG_FloatText 260
#define MSG_FileName 261
#define MSG_DoubleClick 262
#define MSG_PropChoices 263
#define MSG_HorizontalProp 264
#define MSG_EntriesNumber 265
#define MSG_FirstNumber 266
#define MSG_VisibleNumber 267
#define MSG_ScaleTitle 268
#define MSG_Orientation 269
#define MSG_SliderChoice 270
#define MSG_Reverse 271
#define MSG_SliderQuiet 272
#define MSG_UseTitleSlider 273
#define MSG_Minimum 274
#define MSG_Init 275
#define MSG_SliderIdent 276
#define MSG_TextAttributes 277
#define MSG_TextSetMax 278
#define MSG_TextSetMin 279
#define MSG_Backgrounds 280
#define MSG_TextContent 281
#define MSG_Preparse 282
#define MSG_TestWindow 283
#define MSG_TestClick 284
#define MSG_FirstLine 285
#define MSG_SecondLine 286
#define MSG_ThirdLine 287
#define MSG_NotifyTitle 288
#define MSG_InternalError 289
#define MSG_ChoseIdent 290
#define MSG_ChoseVariable 291
#define MSG_Editing 292
#define MSG_Events 293
#define MSG_Actions 294
#define MSG_AddNotify 295
#define MSG_RemoveNotify 296
#define MSG_AddToList 297
#define MSG_RemoveFromList 298
#define MSG_SelectIdentifier 299
#define MSG_IdentifierExists 300
#define MSG_GetConstant 301
#define MSG_IntegerConstant 302
#define MSG_BooleanConstant 303
#define MSG_StringConstant 304
#define MSG_CharConstant 305
#define MSG_Area 306
#define MSG_Hide 307
#define MSG_Disable 308
#define MSG_PhantomFrame 309
#define MSG_Weight 310
#define MSG_Background 311
#define MSG_ControlChar 312
#define MSG_TitleFrame 313
#define MSG_PopUpImage 314
#define MSG_PopFileImage 315
#define MSG_PopDrawerImage 316
#define MSG_FileRequester 317
#define MSG_FontRequester 318
#define MSG_ScreenModeRequester 319
#define MSG_PopAslChoices 320
#define MSG_RequesterType 321
#define MSG_CallHook 322
#define MSG_StartHook 323
#define MSG_StopHook 324
#define MSG_PopObjectChoices 325
#define MSG_Follow 326
#define MSG_Light 327
#define MSG_Volatile 328
#define MSG_Object 329
#define MSG_OpenHook 330
#define MSG_CloseHook 331
#define MSG_ColorfieldChoices 332
#define MSG_Indentification 333
#define MSG_MenuCreation 334
#define MSG_EnableCheck 335
#define MSG_CheckState 336
#define MSG_Toggle 337
#define MSG_ShortCut 338
#define MSG_Enable 339
#define MSG_NewTitle 340
#define MSG_SubMenu 341
#define MSG_MenuItem 342
#define MSG_DeleteMenu 343
#define MSG_Project 344
#define MSG_Merge 345
#define MSG_SaveMenu 346
#define MSG_QuitMenu 347
#define MSG_Fold 348
#define MSG_Unfold 349
#define MSG_About 350
#define MSG_Config 351
#define MSG_Undo 352
#define MSG_Load 353
#define MSG_NewMenu 354
#define MSG_SaveAs 355
#define MSG_EditMenu 356
#define MSG_Tree 357
#define MSG_CatalogPrepend 358
#define MSG_HelpGenerated 359
#define MSG_NotifyHide 360
#define MSG_NotifyShow 361
#define MSG_NotifyDisable 362
#define MSG_NotifyEnable 363
#define MSG_NotifyActivate 364
#define MSG_ReturnID 365
#define MSG_ReturnQuit 366
#define MSG_ApplicationSleep 367
#define MSG_ApplicationWake 368
#define MSG_CallFunction 369
#define MSG_Iconify 370
#define MSG_UnIconify 371
#define MSG_Unactivate 372
#define MSG_OpenWindow 373
#define MSG_CloseWindow 374
#define MSG_Active 375
#define MSG_CloseRequest 376
#define MSG_Deactivate 377
#define MSG_PutTriggerValue 378
#define MSG_PutConstantValue 379
#define MSG_PutVariableValue 380
#define MSG_PressButton 381
#define MSG_ReleaseButton 382
#define MSG_NotifyDisabled 383
#define MSG_NotifyEnabled 384
#define MSG_TimerAction 385
#define MSG_ChangePage 386
#define MSG_Acknowlede 387
#define MSG_ChangePosition 388
#define MSG_ChangeContent 389
#define MSG_ClearList 390
#define MSG_JumpToPosition 391
#define MSG_RedrawAll 392
#define MSG_RedrawActive 393
#define MSG_RemoveActive 394
#define MSG_SortList 395
#define MSG_NotifyDoubleClick 396
#define MSG_ChangeActive 397
#define MSG_ChangeValue 398
#define MSG_ActiveModified 399
#define MSG_Select 400
#define MSG_Unselect 401
#define MSG_SelectOn 402
#define MSG_SelectOff 403
#define MSG_SelectChange 404
#define MSG_PressImage 405
#define MSG_ReleaseImage 406
#define MSG_ChangedPosition 407
#define MSG_NotifyReverse 408
#define MSG_ChangedText 409
#define MSG_ChangedEntriesNumber 410
#define MSG_ChangedVisibleEntries 411
#define MSG_PutTriggerRed 412
#define MSG_PutTriggerBlue 413
#define MSG_PutTriggerGreen 414
#define MSG_PutConstantRed 415
#define MSG_PutConstantGreen 416
#define MSG_PutConstantBlue 417
#define MSG_PutVariableRed 418
#define MSG_PutVariableGreen 419
#define MSG_PutVariableBlue 420
#define MSG_ChangedRed 421
#define MSG_ChangedGreen 422
#define MSG_ChangedBlue 423
#define MSG_ChangeTitleTrigger 424
#define MSG_ChangeTitleVariable 425
#define MSG_ChangeTitleConstant 426
#define MSG_CheckMenuON 427
#define MSG_CheckMenuOFF 428
#define MSG_CheckableON 429
#define MSG_CheckableOFF 430
#define MSG_ChangeShortTrigger 431
#define MSG_ChangeShortVariable 432
#define MSG_ChangeShortConstant 433
#define MSG_ToggleFlagON 434
#define MSG_ToggleFlagOFF 435
#define MSG_MenuTriggered 436
#define MSG_SpaceChoice 437
#define MSG_HorizontalVertical 438
#define MSG_ActiveNoObj 439
#define MSG_ActiveNextObj 440
#define MSG_ActivePrevObj 441
#define MSG_CantFindImages 442
#define MSG_GenerateSource 443
#define MSG_CodeGeneration 444
#define MSG_Misc 445
#define MSG_ImageDrawer 446
#define MSG_GenerateAllIDs 447
#define MSG_NoMenu 448
#define MSG_NeedMouse 449

#endif /*   !MUIBuilder_CAT_H  */
