CC=i386-aros-gcc

.PHONY : all
all:
	$(MAKE) -f Makefile.aros -C src
	$(MAKE) -f Makefile.aros -C Libs/muibuilder/src

.PHONY : clean
clean:
	$(MAKE) -f Makefile.aros clean -C src
	$(MAKE) -f Makefile.aros clean -C Libs/muibuilder/src

.PHONY : distclean
distclean:
	$(MAKE) -f Makefile.aros distclean -C src
	$(MAKE) -f Makefile.aros distclean -C Libs/muibuilder/src
